import Head from 'next/head';
import Title from '../../components/retiro/Title';
import Info from '../../components/retiro/Info';
import Foot from '../../components/Foot';
import Navbar from '../../components/Navbar';
import Formulario from '../../components/retiro/Formulario';


export default function Retiro() {
  return (
    <div className='bg-yellow w-full h-screen'>
      <Head>
        <title>Templo de Tierra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <Title/>
      <Info/>
      <Formulario/>      
      <Foot/>
    </div>
  )
}
